name: Tests
run-name: ${{ github.actor }} launching tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/setup-python@v5
      - name: setup python
        uses: actions/setup-python@v5
      - run: pip install .
      - run: pip install pytest pytest-cov
      - run: pytest src --cov=src

