name: 'Setup Python environment'
description: 'Prepare Python environment for testing'
inputs:
  extra_package:
    description: 'Additional packages to install'
    required: false
    default: ''
runs:
  steps:
    - name: install package
      run: pip install .
    - name: install extra-packages
      if: '${{ inputs.extra_package }} != "" '
      run: pip install ${{ inputs.extra_package }}
  