name: Tests
run-name: ${{ github.actor }} launching tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: setup python
        uses: actions/checkout@v4
      - name: checkout repo
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install .
      - run: pip install pytest pytest-cov
      - run: pytest src --cov=src

